/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotelmanagement.system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bill
 */
public class Home extends javax.swing.JFrame {

    JPanelLoader load=new JPanelLoader();
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    String userType;
    public Home(String username, BufferedImage imag, String userType) {
        initComponents();
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        this.username=username;
        this.imag=imag;
        this.userType=userType;
        user_filtration();
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("emmanuel-chigbo-jr7R01lOn1Y-unsplash.jpg")).getImage().getScaledInstance(1280, 720, Image.SCALE_SMOOTH)));
        //lblPanel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("social-3064515_1920.jpg")).getImage().getScaledInstance(lblPanel.getWidth(), lblPanel.getHeight(), Image.SCALE_SMOOTH)));
    }

    
    public void user_filtration(){
        if(userType.trim().equals("ADMIN")){
            hotelMenu.setVisible(true);
            storeMenu.setVisible(true);
            financeMenu.setVisible(true);
            userAccountsMenu.setVisible(true);
            departmentalOrdersMenu.setVisible(true);
            departmentsMenu.setVisible(true);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("SECURITY")){
            hotelMenu.setVisible(false);
            storeMenu.setVisible(false);
            financeMenu.setVisible(false);
            userAccountsMenu.setVisible(false);
            departmentalOrdersMenu.setVisible(true);
            departmentsMenu.setVisible(true);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("STORE KEEPER")){
            hotelMenu.setVisible(false);
            storeMenu.setVisible(true);
            financeMenu.setVisible(false);
            userAccountsMenu.setVisible(false);
            departmentalOrdersMenu.setVisible(false);
            departmentsMenu.setVisible(true);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("HOTEL CASHIER")){
            hotelMenu.setVisible(true);
            storeMenu.setVisible(false);
            financeMenu.setVisible(false);
            userAccountsMenu.setVisible(false);
            departmentalOrdersMenu.setVisible(true);
            departmentsMenu.setVisible(true);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("KITCHEN DPT")){
            hotelMenu.setVisible(false);
            storeMenu.setVisible(false);
            financeMenu.setVisible(false);
            userAccountsMenu.setVisible(false);
            departmentalOrdersMenu.setVisible(true);
            departmentsMenu.setVisible(true);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("FINANCE DPT")){
            hotelMenu.setVisible(false);
            storeMenu.setVisible(false);
            financeMenu.setVisible(true);
            userAccountsMenu.setVisible(false);
            departmentalOrdersMenu.setVisible(false);
            departmentsMenu.setVisible(false);
            aboutAuthorMenu.setVisible(true);
        }else if(userType.trim().equals("OTHER")){

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        hotelMenu = new javax.swing.JMenu();
        ManageClientsItem = new javax.swing.JMenuItem();
        ViewRoomMenu = new javax.swing.JMenuItem();
        roomBookingsMenu = new javax.swing.JMenuItem();
        hotelRoomsMenu = new javax.swing.JMenuItem();
        roomIncomeMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        availableMealsMenu = new javax.swing.JMenuItem();
        sellMealsMenu = new javax.swing.JMenuItem();
        mealSalesMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        exitMenu1 = new javax.swing.JMenuItem();
        storeMenu = new javax.swing.JMenu();
        stockInStoreMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        checkDepartmentalOrdersMenu = new javax.swing.JMenuItem();
        issueStoreItemsMenu = new javax.swing.JMenuItem();
        receivedOrderdItemsMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        messageFinanceMenu = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        exitSystemMenu = new javax.swing.JMenuItem();
        exitMenu3 = new javax.swing.JMenuItem();
        financeMenu = new javax.swing.JMenu();
        addSuppliersMenu = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        manageTendersMenu = new javax.swing.JMenuItem();
        paySuppliersMenu = new javax.swing.JMenuItem();
        viewPaymentsMenu = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        messageStoreMenu = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        exitMenu2 = new javax.swing.JMenuItem();
        exitMenu4 = new javax.swing.JMenuItem();
        userAccountsMenu = new javax.swing.JMenu();
        createUsers = new javax.swing.JMenuItem();
        viewUsers = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        exit1 = new javax.swing.JMenuItem();
        exitMenu5 = new javax.swing.JMenuItem();
        departmentalOrdersMenu = new javax.swing.JMenu();
        orderStoreItemsMenu = new javax.swing.JMenuItem();
        reveiveOrderItems = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        exit2 = new javax.swing.JMenuItem();
        exitMenu6 = new javax.swing.JMenuItem();
        departmentsMenu = new javax.swing.JMenu();
        addDepartmentsMenu = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        exit3 = new javax.swing.JMenuItem();
        exitMenu7 = new javax.swing.JMenuItem();
        aboutAuthorMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        exit4Menu = new javax.swing.JMenuItem();
        exitMenu8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1250, 720, 720, 720));
        setMaximumSize(new java.awt.Dimension(1250, 720));
        setMinimumSize(new java.awt.Dimension(1250, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(29, 122, 53));
        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setMaximumSize(new java.awt.Dimension(1140, 600));
        panel.setMinimumSize(new java.awt.Dimension(1140, 600));
        panel.setPreferredSize(new java.awt.Dimension(1140, 600));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("With User Friendly and Advanced Features");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Welcome to Five Star * Hotel Order Management System");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1140, 600));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        hotelMenu.setText("Hotel");

        ManageClientsItem.setText("Manage Clients");
        ManageClientsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageClientsItemActionPerformed(evt);
            }
        });
        hotelMenu.add(ManageClientsItem);

        ViewRoomMenu.setText("View Room Allocation");
        ViewRoomMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRoomMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(ViewRoomMenu);

        roomBookingsMenu.setText("View Room Bookings");
        roomBookingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomBookingsMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(roomBookingsMenu);

        hotelRoomsMenu.setText("Hotel Rooms");
        hotelRoomsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRoomsMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(hotelRoomsMenu);

        roomIncomeMenu.setText("View Room Income");
        roomIncomeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomIncomeMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(roomIncomeMenu);
        hotelMenu.add(jSeparator1);

        availableMealsMenu.setText("Available Meals");
        availableMealsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableMealsMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(availableMealsMenu);

        sellMealsMenu.setText("Sell Meals");
        sellMealsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMealsMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(sellMealsMenu);

        mealSalesMenu.setText("View Meal Sales");
        mealSalesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealSalesMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(mealSalesMenu);
        hotelMenu.add(jSeparator2);

        exitMenu.setText("Exit System");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        hotelMenu.add(exitMenu);

        exitMenu1.setText("Log Out");
        exitMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu1ActionPerformed(evt);
            }
        });
        hotelMenu.add(exitMenu1);

        jMenuBar1.add(hotelMenu);

        storeMenu.setText("Store");

        stockInStoreMenu.setText("Stock In Store");
        stockInStoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInStoreMenuActionPerformed(evt);
            }
        });
        storeMenu.add(stockInStoreMenu);
        storeMenu.add(jSeparator3);

        checkDepartmentalOrdersMenu.setText("Check Departmental Orders");
        checkDepartmentalOrdersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDepartmentalOrdersMenuActionPerformed(evt);
            }
        });
        storeMenu.add(checkDepartmentalOrdersMenu);

        issueStoreItemsMenu.setText("Issue Store Items");
        issueStoreItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueStoreItemsMenuActionPerformed(evt);
            }
        });
        storeMenu.add(issueStoreItemsMenu);

        receivedOrderdItemsMenu.setText("View Received Ordered Items");
        receivedOrderdItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedOrderdItemsMenuActionPerformed(evt);
            }
        });
        storeMenu.add(receivedOrderdItemsMenu);
        storeMenu.add(jSeparator4);

        messageFinanceMenu.setText("Message Finance Department");
        messageFinanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFinanceMenuActionPerformed(evt);
            }
        });
        storeMenu.add(messageFinanceMenu);
        storeMenu.add(jSeparator5);

        exitSystemMenu.setText("Exit System");
        exitSystemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSystemMenuActionPerformed(evt);
            }
        });
        storeMenu.add(exitSystemMenu);

        exitMenu3.setText("Log Out");
        exitMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu3ActionPerformed(evt);
            }
        });
        storeMenu.add(exitMenu3);

        jMenuBar1.add(storeMenu);

        financeMenu.setText("Finance");

        addSuppliersMenu.setText("Add Suppliers");
        addSuppliersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSuppliersMenuActionPerformed(evt);
            }
        });
        financeMenu.add(addSuppliersMenu);
        financeMenu.add(jSeparator6);

        manageTendersMenu.setText("Manage Tenders");
        manageTendersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTendersMenuActionPerformed(evt);
            }
        });
        financeMenu.add(manageTendersMenu);

        paySuppliersMenu.setText("Pay Suppliers");
        paySuppliersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySuppliersMenuActionPerformed(evt);
            }
        });
        financeMenu.add(paySuppliersMenu);

        viewPaymentsMenu.setText("View Payments");
        viewPaymentsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentsMenuActionPerformed(evt);
            }
        });
        financeMenu.add(viewPaymentsMenu);
        financeMenu.add(jSeparator7);

        messageStoreMenu.setText("Message Store");
        messageStoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageStoreMenuActionPerformed(evt);
            }
        });
        financeMenu.add(messageStoreMenu);
        financeMenu.add(jSeparator8);

        exitMenu2.setText("Exit System");
        exitMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu2ActionPerformed(evt);
            }
        });
        financeMenu.add(exitMenu2);

        exitMenu4.setText("Log Out");
        exitMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu4ActionPerformed(evt);
            }
        });
        financeMenu.add(exitMenu4);

        jMenuBar1.add(financeMenu);

        userAccountsMenu.setText("User Accounts");

        createUsers.setText("Create New Users");
        createUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUsersActionPerformed(evt);
            }
        });
        userAccountsMenu.add(createUsers);

        viewUsers.setText("View & Edit Users");
        viewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersActionPerformed(evt);
            }
        });
        userAccountsMenu.add(viewUsers);
        userAccountsMenu.add(jSeparator9);

        exit1.setText("Exit System");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        userAccountsMenu.add(exit1);

        exitMenu5.setText("Log Out");
        exitMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu5ActionPerformed(evt);
            }
        });
        userAccountsMenu.add(exitMenu5);

        jMenuBar1.add(userAccountsMenu);

        departmentalOrdersMenu.setText("Departmental Orders");

        orderStoreItemsMenu.setText("Order Store Items");
        orderStoreItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStoreItemsMenuActionPerformed(evt);
            }
        });
        departmentalOrdersMenu.add(orderStoreItemsMenu);

        reveiveOrderItems.setText("Receive Ordered Items");
        reveiveOrderItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reveiveOrderItemsActionPerformed(evt);
            }
        });
        departmentalOrdersMenu.add(reveiveOrderItems);
        departmentalOrdersMenu.add(jSeparator10);

        exit2.setText("Exit System");
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });
        departmentalOrdersMenu.add(exit2);

        exitMenu6.setText("Log Out");
        exitMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu6ActionPerformed(evt);
            }
        });
        departmentalOrdersMenu.add(exitMenu6);

        jMenuBar1.add(departmentalOrdersMenu);

        departmentsMenu.setText("Departments");

        addDepartmentsMenu.setText("Add & Edit Departments");
        addDepartmentsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentsMenuActionPerformed(evt);
            }
        });
        departmentsMenu.add(addDepartmentsMenu);
        departmentsMenu.add(jSeparator11);

        exit3.setText("Exit System");
        exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit3ActionPerformed(evt);
            }
        });
        departmentsMenu.add(exit3);

        exitMenu7.setText("Log Out");
        exitMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu7ActionPerformed(evt);
            }
        });
        departmentsMenu.add(exitMenu7);

        jMenuBar1.add(departmentsMenu);

        aboutAuthorMenu.setText("About");

        aboutMenu.setText("About System");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        aboutAuthorMenu.add(aboutMenu);
        aboutAuthorMenu.add(jSeparator12);

        exit4Menu.setText("Exit System");
        exit4Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit4MenuActionPerformed(evt);
            }
        });
        aboutAuthorMenu.add(exit4Menu);

        exitMenu8.setText("Log Out");
        exitMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu8ActionPerformed(evt);
            }
        });
        aboutAuthorMenu.add(exitMenu8);

        jMenuBar1.add(aboutAuthorMenu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuActionPerformed

    private void addSuppliersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuppliersMenuActionPerformed
        Suppliers1 suppliers=new Suppliers1(username,imag,userType);
        load.jPanelLoader(panel, suppliers);
    }//GEN-LAST:event_addSuppliersMenuActionPerformed

    private void addDepartmentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentsMenuActionPerformed
        Departments1 departments=new Departments1(username,imag,userType);
        load.jPanelLoader(panel, departments);
    }//GEN-LAST:event_addDepartmentsMenuActionPerformed

    private void ManageClientsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageClientsItemActionPerformed
        ManageClients1 manage=new ManageClients1(username,imag,userType);
        load.jPanelLoader(panel, manage);
    }//GEN-LAST:event_ManageClientsItemActionPerformed

    private void ViewRoomMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRoomMenuActionPerformed
        ViewRoomAllocations1 rooms=new ViewRoomAllocations1(username,imag,userType);
        load.jPanelLoader(panel, rooms);
    }//GEN-LAST:event_ViewRoomMenuActionPerformed

    private void hotelRoomsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRoomsMenuActionPerformed
        AvailableRooms1 rooms=new AvailableRooms1(username,imag,userType);
        load.jPanelLoader(panel, rooms);
    }//GEN-LAST:event_hotelRoomsMenuActionPerformed

    private void roomBookingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomBookingsMenuActionPerformed
        ViewRoomBookings1 rooms=new ViewRoomBookings1(username,imag,userType);
        load.jPanelLoader(panel, rooms);
    }//GEN-LAST:event_roomBookingsMenuActionPerformed

    private void roomIncomeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomIncomeMenuActionPerformed
        HotelIncome1 income=new HotelIncome1(username,imag,userType);
        load.jPanelLoader(panel, income);
    }//GEN-LAST:event_roomIncomeMenuActionPerformed

    private void availableMealsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableMealsMenuActionPerformed
        HotelMeals1 meals=new HotelMeals1(username,imag,userType);
        load.jPanelLoader(panel, meals);
    }//GEN-LAST:event_availableMealsMenuActionPerformed

    private void sellMealsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMealsMenuActionPerformed
        SellMeals1 meals=new SellMeals1(username,imag,userType);
        load.jPanelLoader(panel, meals);
    }//GEN-LAST:event_sellMealsMenuActionPerformed

    private void mealSalesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealSalesMenuActionPerformed
        ViewSales1 sales=new ViewSales1(username,imag,userType);
        load.jPanelLoader(panel, sales);
    }//GEN-LAST:event_mealSalesMenuActionPerformed

    private void exitMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu1ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu1ActionPerformed

    private void exitSystemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSystemMenuActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitSystemMenuActionPerformed

    private void exitMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu2ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenu2ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exit1ActionPerformed

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exit2ActionPerformed

    private void exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit3ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exit3ActionPerformed

    private void exit4MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit4MenuActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Order Management System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exit4MenuActionPerformed

    private void stockInStoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInStoreMenuActionPerformed
        StockInStore1 stock=new StockInStore1(username,imag,userType);
        load.jPanelLoader(panel, stock);
    }//GEN-LAST:event_stockInStoreMenuActionPerformed

    private void checkDepartmentalOrdersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDepartmentalOrdersMenuActionPerformed
        CheckDepartmentalOrders1 orders=new CheckDepartmentalOrders1(username,imag,userType);
        load.jPanelLoader(panel, orders);
    }//GEN-LAST:event_checkDepartmentalOrdersMenuActionPerformed

    private void issueStoreItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueStoreItemsMenuActionPerformed
        IssueItems1 stock=new IssueItems1(username,imag,userType);
        load.jPanelLoader(panel, stock);
    }//GEN-LAST:event_issueStoreItemsMenuActionPerformed

    private void receivedOrderdItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedOrderdItemsMenuActionPerformed
        ViewReceivedOrderedItems1 items=new ViewReceivedOrderedItems1(username,imag,userType);
        load.jPanelLoader(panel, items);
    }//GEN-LAST:event_receivedOrderdItemsMenuActionPerformed

    private void messageFinanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFinanceMenuActionPerformed
        MessagesFinance1 messages=new MessagesFinance1(username,imag,userType);
        load.jPanelLoader(panel, messages);
    }//GEN-LAST:event_messageFinanceMenuActionPerformed

    private void manageTendersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTendersMenuActionPerformed
        ManageTenders1 manage=new ManageTenders1(username,imag,userType);
        load.jPanelLoader(panel, manage);
    }//GEN-LAST:event_manageTendersMenuActionPerformed

    private void paySuppliersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySuppliersMenuActionPerformed
        PaySuppliers1 pay=new PaySuppliers1(username,imag,userType);
        load.jPanelLoader(panel, pay);
    }//GEN-LAST:event_paySuppliersMenuActionPerformed

    private void viewPaymentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentsMenuActionPerformed
        ViewPayments1 view=new ViewPayments1(username,imag,userType);
        load.jPanelLoader(panel, view);
    }//GEN-LAST:event_viewPaymentsMenuActionPerformed

    private void messageStoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageStoreMenuActionPerformed
        Messages1 messages=new Messages1(username,imag,userType);
        load.jPanelLoader(panel, messages);
    }//GEN-LAST:event_messageStoreMenuActionPerformed

    private void createUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUsersActionPerformed
        User1 user=new User1(username,imag,userType);
        load.jPanelLoader(panel, user);
    }//GEN-LAST:event_createUsersActionPerformed

    private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
        EditUsers1 edit=new EditUsers1(username,imag,userType);
        load.jPanelLoader(panel, edit);
    }//GEN-LAST:event_viewUsersActionPerformed

    private void orderStoreItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStoreItemsMenuActionPerformed
        OrderStoreItems1 order=new OrderStoreItems1(username,imag,userType);
        load.jPanelLoader(panel, order);
    }//GEN-LAST:event_orderStoreItemsMenuActionPerformed

    private void reveiveOrderItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reveiveOrderItemsActionPerformed
        ReceiveStoreItems1 receice=new ReceiveStoreItems1(username,imag,userType);
        load.jPanelLoader(panel, receice);
    }//GEN-LAST:event_reveiveOrderItemsActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        About1 about=new About1(username,imag,userType);
        load.jPanelLoader(panel, about);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void exitMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu3ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu3ActionPerformed

    private void exitMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu4ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu4ActionPerformed

    private void exitMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu5ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu5ActionPerformed

    private void exitMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu6ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu6ActionPerformed

    private void exitMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu7ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu7ActionPerformed

    private void exitMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu8ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to log out of Order Management System?","Confirm Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitMenu8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ManageClientsItem;
    private javax.swing.JMenuItem ViewRoomMenu;
    private javax.swing.JMenu aboutAuthorMenu;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem addDepartmentsMenu;
    private javax.swing.JMenuItem addSuppliersMenu;
    private javax.swing.JMenuItem availableMealsMenu;
    private javax.swing.JMenuItem checkDepartmentalOrdersMenu;
    private javax.swing.JMenuItem createUsers;
    private javax.swing.JMenu departmentalOrdersMenu;
    private javax.swing.JMenu departmentsMenu;
    private javax.swing.JMenuItem exit1;
    private javax.swing.JMenuItem exit2;
    private javax.swing.JMenuItem exit3;
    private javax.swing.JMenuItem exit4Menu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem exitMenu1;
    private javax.swing.JMenuItem exitMenu2;
    private javax.swing.JMenuItem exitMenu3;
    private javax.swing.JMenuItem exitMenu4;
    private javax.swing.JMenuItem exitMenu5;
    private javax.swing.JMenuItem exitMenu6;
    private javax.swing.JMenuItem exitMenu7;
    private javax.swing.JMenuItem exitMenu8;
    private javax.swing.JMenuItem exitSystemMenu;
    private javax.swing.JMenu financeMenu;
    private javax.swing.JMenu hotelMenu;
    private javax.swing.JMenuItem hotelRoomsMenu;
    private javax.swing.JMenuItem issueStoreItemsMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenuItem manageTendersMenu;
    private javax.swing.JMenuItem mealSalesMenu;
    private javax.swing.JMenuItem messageFinanceMenu;
    private javax.swing.JMenuItem messageStoreMenu;
    private javax.swing.JMenuItem orderStoreItemsMenu;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem paySuppliersMenu;
    private javax.swing.JMenuItem receivedOrderdItemsMenu;
    private javax.swing.JMenuItem reveiveOrderItems;
    private javax.swing.JMenuItem roomBookingsMenu;
    private javax.swing.JMenuItem roomIncomeMenu;
    private javax.swing.JMenuItem sellMealsMenu;
    private javax.swing.JMenuItem stockInStoreMenu;
    private javax.swing.JMenu storeMenu;
    private javax.swing.JMenu userAccountsMenu;
    private javax.swing.JMenuItem viewPaymentsMenu;
    private javax.swing.JMenuItem viewUsers;
    // End of variables declaration//GEN-END:variables
}
