/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotelmanagement.system;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bill
 */
public class Suppliers1 extends javax.swing.JPanel {

    PreparedStatement pst;
    ResultSet rs;
    Database base=new Database();
    Connection con=base.myCon();
    /**
     * Creates new form Suppliers1
     */
    public Suppliers1() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    String userType;
    public Suppliers1(String username, BufferedImage imag, String userType) {
        initComponents();
        suppliers_Table();
        Auto_id();
        this.username=username;
        lblUsername.setText(username);
        this.imag=imag;
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH)));
        //lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("social-3064515_1920.jpg")).getImage().getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), Image.SCALE_SMOOTH)));
        this.userType=userType;
        lblUserType.setText(userType);
        button_pre_enabled();
    }
    
    public void button_pre_enabled(){
        editBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }
    
    public void Auto_id(){
        try {
            Statement s=con.createStatement();
            rs=s.executeQuery("select MAX(suppNo) from suppliers");
            rs.next();
            rs.getString("MAX(suppNo)");
            if(rs.getString("MAX(suppNo)")==null){
                lblSuppNo.setText("SU001");
            }else{
                long id=Long.parseLong(rs.getString("MAX(suppNo)").substring(2,rs.getString("MAX(suppNo)").length()));
                id++;
                lblSuppNo.setText("SU"+String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void suppliers_Table(){
        try {
            pst=con.prepareStatement("select * from suppliers");
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();
            
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<c;i++){
                    v.add(rs.getString("suppNo"));
                    v.add(rs.getString("supplier"));
                    v.add(rs.getString("email"));
                    v.add(rs.getString("phone"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("accNo"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblSuppNo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        exitBtn1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1140, 600));
        setMinimumSize(new java.awt.Dimension(1140, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(155, 31, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfile.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 90, 90));

        lblUsername.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsername.setForeground(java.awt.Color.white);
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USERNAME");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 180, -1));

        lblUserType.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserType.setForeground(java.awt.Color.white);
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setText("USER TYPE");
        jPanel1.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 180, -1));

        lblSuppNo.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        lblSuppNo.setForeground(java.awt.Color.white);
        lblSuppNo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        jPanel1.add(lblSuppNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 40));

        jLabel10.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("SUPP NO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("NAME:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 200, 40));

        clearBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(128, 13, 238));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 50));

        addBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 22, 255));
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 50));

        editBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(29, 165, 51));
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 50));

        exitBtn1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exitBtn1.setForeground(new java.awt.Color(238, 13, 24));
        exitBtn1.setText("EXIT");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 50));

        deleteBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(238, 13, 24));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 50));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SUPP NO", "SUPPLIER", "EMAIL", "PHONE", "ADDRESS", "ACC NO"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 760, 370));

        jLabel6.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("EMAIL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 200, 40));

        jLabel7.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("PHONE NO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 40));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 260, -1));

        btnSearch.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        btnSearch.setText("SEARCH WITH SUPPLIER'S NAME");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 310, -1));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 40));

        jLabel8.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("ADDRESS:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("ACC NO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, -1));

        txtAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccNoKeyPressed(evt);
            }
        });
        jPanel1.add(txtAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1120, 510));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 17, 239));
        jLabel1.setText("ADD - EDIT SUPPLIERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 690, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtEmail.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtEmail.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtAccNo.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtAccNo.setText("");
        txtName.requestFocus();
        suppliers_Table();
        Auto_id();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String suppNo=lblSuppNo.getText();
        String suppName=txtName.getText();
        String email=txtEmail.getText();
        String phone=txtPhone.getText();
        String address=txtAddress.getText();
        String accNo=txtAccNo.getText();

        if(txtName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's name, null supplier's names cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtName.requestFocus();
        }else if(txtEmail.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's email, null supplier's name cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtEmail.requestFocus();
        }else if(txtPhone.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's phone nummber, null supplier's phone numbers cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtPhone.requestFocus();
        }else if(txtAddress.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's Address location, null supplier's addresses cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtAddress.requestFocus();
        }else if(txtAccNo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's Account Number, null supplier's account numbers cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtAccNo.requestFocus();
        }else{
            try {
                pst=con.prepareStatement("insert into suppliers(suppNo,supplier,email,phone,address,accNo)values(?,?,?,?,?,?)");
                pst.setString(1, suppNo);
                pst.setString(2, suppName);
                pst.setString(3, email);
                pst.setString(4, phone);
                pst.setString(5, address);
                pst.setString(6, accNo);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Supplier added successfully into database","Success Message",JOptionPane.INFORMATION_MESSAGE);
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtAccNo.setText("");
                txtName.requestFocus();
                suppliers_Table();
                Auto_id();
            } catch (SQLException ex) {
                Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String suppNo=lblSuppNo.getText();
        String suppName=txtName.getText();
        String email=txtEmail.getText();
        String phone=txtPhone.getText();
        String address=txtAddress.getText();
        String accNo=txtAccNo.getText();

        if(txtName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's name, null supplier's names cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtName.requestFocus();
        }else if(txtEmail.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's email, null supplier's name cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtEmail.requestFocus();
        }else if(txtPhone.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's phone nummber, null supplier's phone numbers cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtPhone.requestFocus();
        }else if(txtAddress.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's Address location, null supplier's addresses cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtAddress.requestFocus();
        }else if(txtAccNo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a supplier's Account Number, null supplier's account numbers cannot submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtAccNo.requestFocus();
        }else{
            try {
                pst=con.prepareStatement("update suppliers set supplier=?,email=?,phone=?,address=?, accNo=? where suppNo=?");
                pst.setString(1, suppName);
                pst.setString(2, email);
                pst.setString(3, phone);
                pst.setString(4, address);
                pst.setString(5, accNo);
                pst.setString(6, suppNo);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Supplier Updated successfully on database","Success Message",JOptionPane.INFORMATION_MESSAGE);
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtAccNo.setText("");
                txtName.requestFocus();
                txtName.requestFocus();
                editBtn.setEnabled(false);
                deleteBtn.setEnabled(false);
                addBtn.setEnabled(true);
                suppliers_Table();
                Auto_id();
            } catch (SQLException ex) {
                Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Hotel System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtn1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String suppNo=lblSuppNo.getText();

        if(txtName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please select supplier, null suppliers cannot deleted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtName.requestFocus();
        }else{
            try {
                pst=con.prepareStatement("delete from suppliers where suppNo=?");
                pst.setString(1, suppNo);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Supplier deleted successfully from database","Success Message",JOptionPane.INFORMATION_MESSAGE);
                txtName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                txtAddress.setText("");
                txtAccNo.setText("");
                txtName.requestFocus();
                txtName.requestFocus();
                editBtn.setEnabled(false);
                deleteBtn.setEnabled(false);
                addBtn.setEnabled(true);
                suppliers_Table();
                Auto_id();
            } catch (SQLException ex) {
                Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        editBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        addBtn.setEnabled(false);

        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int selectedIndex=table.getSelectedRow();
        lblSuppNo.setText(model.getValueAt(selectedIndex, 0).toString());
        txtName.setText(model.getValueAt(selectedIndex, 1).toString());
        txtEmail.setText(model.getValueAt(selectedIndex, 2).toString());
        txtPhone.setText(model.getValueAt(selectedIndex, 3).toString());
        txtAddress.setText(model.getValueAt(selectedIndex, 4).toString());
        txtAccNo.setText(model.getValueAt(selectedIndex, 5).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPhone.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPhone.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtAddress.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtAddress.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String suppName=txtSearch.getText();
            try {
                pst=con.prepareStatement("select * from suppliers where supplier LIKE CONCAT('%',?,'%')");
                pst.setString(1, suppName);
                rs=pst.executeQuery();
                ResultSetMetaData rsm=rs.getMetaData();
                int c=rsm.getColumnCount();

                DefaultTableModel model=(DefaultTableModel)table.getModel();
                model.setRowCount(0);
                while(rs.next()){
                    Vector v=new Vector();
                    for(int i=1;i<c;i++){
                        v.add(rs.getString("suppNo"));
                        v.add(rs.getString("supplier"));
                        v.add(rs.getString("email"));
                        v.add(rs.getString("phone"));
                        v.add(rs.getString("address"));
                        v.add(rs.getString("accNo"));
                    }
                    model.addRow(v);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String suppName=txtSearch.getText();
        try {
            pst=con.prepareStatement("select * from suppliers where supplier LIKE CONCAT('%',?,'%')");
            pst.setString(1, suppName);
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();

            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<c;i++){
                    v.add(rs.getString("suppNo"));
                    v.add(rs.getString("supplier"));
                    v.add(rs.getString("email"));
                    v.add(rs.getString("phone"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("accNo"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtAccNo.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtAccNo.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPhone.requestFocus();
        }
    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtAccNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccNoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtName.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtName.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtAddress.requestFocus();
        }
    }//GEN-LAST:event_txtAccNoKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String suppName=txtSearch.getText();
        try {
            pst=con.prepareStatement("select * from suppliers where supplier LIKE CONCAT('%',?,'%')");
            pst.setString(1, suppName);
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();

            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<c;i++){
                    v.add(rs.getString("suppNo"));
                    v.add(rs.getString("supplier"));
                    v.add(rs.getString("email"));
                    v.add(rs.getString("phone"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("accNo"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Suppliers1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblSuppNo;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
