/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotelmanagement.system;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bill
 */
public class Main extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    String userType;
    public Main(String username, BufferedImage imag, String userType) {
        initComponents();
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("emmanuel-chigbo-jr7R01lOn1Y-unsplash.jpg")).getImage().getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), Image.SCALE_SMOOTH)));
        this.username=username;
        lblUsername.setText(username);
        this.imag=imag;
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        this.userType=userType;
        lblUserType.setText(userType);
        Connect();
        
        
        //STORE PANEL
        lblUsernameStore.setText(username);
        lblProfileStore.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        userTypeStore.setText(userType);
        
        //FINANCE PANEL
        lblUsernameFinance.setText(username);
        lblProfileFinance.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        lblUserTypeFinance.setText(userType);
        //USER ACCOUNTS PANEL
        lblUsernameAccounts.setText(username);
        lblProfileAccounts.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        lblUserTypeAccounts.setText(userType);
        //KITCHEN PANEL
        lblUsernameKitchen.setText(username);
        lblProfileKitchen.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        lblUserTypeKitchen.setText(userType);
        //ABOUT PANEL
        lblUsernameDepartments.setText(username);
        lblProfileDepartments.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        lblUserTypeDepartments.setText(userType);
    }

    /*public void Connect(){
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:Hotel.db");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/orderMgmt","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        hotelRooms = new javax.swing.JButton();
        roomBooking = new javax.swing.JButton();
        addClientBtn = new javax.swing.JButton();
        meals = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        meals1 = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        salesViewBtn = new javax.swing.JButton();
        lblUserType = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProfileStore = new javax.swing.JLabel();
        lblUsernameStore = new javax.swing.JLabel();
        stockInStoreBtn = new javax.swing.JButton();
        issueStoreItemsBtn = new javax.swing.JButton();
        receiveItemsBtn = new javax.swing.JButton();
        userTypeStore = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblProfileFinance = new javax.swing.JLabel();
        lblUsernameFinance = new javax.swing.JLabel();
        supplierPaymentBtn = new javax.swing.JButton();
        addSuppliersBtn = new javax.swing.JButton();
        tenderBtn = new javax.swing.JButton();
        lblUserTypeFinance = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblProfileAccounts = new javax.swing.JLabel();
        lblUsernameAccounts = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        newUserBtn = new javax.swing.JButton();
        lblUserTypeAccounts = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblProfileKitchen = new javax.swing.JLabel();
        lblUsernameKitchen = new javax.swing.JLabel();
        lblUserTypeKitchen = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        addDepartments = new javax.swing.JToggleButton();
        lblProfileDepartments = new javax.swing.JLabel();
        lblUserTypeDepartments = new javax.swing.JLabel();
        lblUsernameDepartments = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME PAGE");
        setMaximizedBounds(new java.awt.Rectangle(1280, 720, 720, 720));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(142, 54, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotelRooms.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        hotelRooms.setForeground(new java.awt.Color(13, 52, 248));
        hotelRooms.setText("HOTEL ROOMS");
        hotelRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRoomsActionPerformed(evt);
            }
        });
        jPanel1.add(hotelRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 230, 50));

        roomBooking.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        roomBooking.setForeground(new java.awt.Color(13, 52, 248));
        roomBooking.setText("ROOM BOOKING");
        roomBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomBookingActionPerformed(evt);
            }
        });
        jPanel1.add(roomBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 50));

        addClientBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addClientBtn.setForeground(new java.awt.Color(13, 52, 248));
        addClientBtn.setText("ADD CLIENT");
        addClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addClientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 50));

        meals.setBackground(new java.awt.Color(41, 194, 52));
        meals.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        meals.setForeground(java.awt.Color.white);
        meals.setText("AVALABLE MEALS");
        meals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsActionPerformed(evt);
            }
        });
        jPanel1.add(meals, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 50));

        exitBtn.setBackground(new java.awt.Color(247, 63, 9));
        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        exitBtn.setForeground(java.awt.Color.white);
        exitBtn.setText("EXIT SYSTEM");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, 50));

        meals1.setBackground(new java.awt.Color(15, 19, 247));
        meals1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        meals1.setForeground(java.awt.Color.white);
        meals1.setText("SELL MEALS");
        meals1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meals1ActionPerformed(evt);
            }
        });
        jPanel1.add(meals1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 50));

        lblProfile.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 150, 170));

        lblUsername.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsername.setForeground(java.awt.Color.white);
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USERNAME");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 180, -1));

        salesViewBtn.setBackground(new java.awt.Color(15, 47, 240));
        salesViewBtn.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        salesViewBtn.setForeground(java.awt.Color.white);
        salesViewBtn.setText("VIEW MEAL SALES");
        salesViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(salesViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 230, 50));

        lblUserType.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserType.setForeground(java.awt.Color.white);
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setText("USER TYPE");
        jPanel1.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        jTabbedPane1.addTab("HOTEL", jPanel1);

        jPanel3.setBackground(new java.awt.Color(36, 149, 30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileStore.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel3.add(lblProfileStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 150, 170));

        lblUsernameStore.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsernameStore.setForeground(java.awt.Color.white);
        lblUsernameStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameStore.setText("USERNAME");
        jPanel3.add(lblUsernameStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 180, -1));

        stockInStoreBtn.setBackground(new java.awt.Color(220, 15, 15));
        stockInStoreBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        stockInStoreBtn.setForeground(java.awt.Color.white);
        stockInStoreBtn.setText("STOCK IN STORE");
        stockInStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInStoreBtnActionPerformed(evt);
            }
        });
        jPanel3.add(stockInStoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 50));

        issueStoreItemsBtn.setBackground(new java.awt.Color(34, 44, 246));
        issueStoreItemsBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        issueStoreItemsBtn.setForeground(java.awt.Color.white);
        issueStoreItemsBtn.setText("ISSUE STORE ITEMS");
        issueStoreItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueStoreItemsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(issueStoreItemsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 250, 50));

        receiveItemsBtn.setBackground(new java.awt.Color(34, 44, 246));
        receiveItemsBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        receiveItemsBtn.setForeground(java.awt.Color.white);
        receiveItemsBtn.setText("RECEIVE ITEMS");
        receiveItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveItemsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(receiveItemsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 50));

        userTypeStore.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        userTypeStore.setForeground(java.awt.Color.white);
        userTypeStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTypeStore.setText("USER TYPE");
        jPanel3.add(userTypeStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        jTabbedPane1.addTab("STORE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(230, 9, 236));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileFinance.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel4.add(lblProfileFinance, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 150, 170));

        lblUsernameFinance.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsernameFinance.setForeground(java.awt.Color.white);
        lblUsernameFinance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameFinance.setText("USERNAME");
        jPanel4.add(lblUsernameFinance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 180, -1));

        supplierPaymentBtn.setBackground(java.awt.Color.blue);
        supplierPaymentBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        supplierPaymentBtn.setForeground(java.awt.Color.white);
        supplierPaymentBtn.setText("PAY SUPPLIERS");
        supplierPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierPaymentBtnActionPerformed(evt);
            }
        });
        jPanel4.add(supplierPaymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 50));

        addSuppliersBtn.setBackground(java.awt.Color.blue);
        addSuppliersBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addSuppliersBtn.setForeground(java.awt.Color.white);
        addSuppliersBtn.setText("ADD SUPPLIERS");
        addSuppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSuppliersBtnActionPerformed(evt);
            }
        });
        jPanel4.add(addSuppliersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 50));

        tenderBtn.setBackground(java.awt.Color.blue);
        tenderBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tenderBtn.setForeground(java.awt.Color.white);
        tenderBtn.setText("EVALUATE TENDERS");
        tenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenderBtnActionPerformed(evt);
            }
        });
        jPanel4.add(tenderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 50));

        lblUserTypeFinance.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserTypeFinance.setForeground(java.awt.Color.white);
        lblUserTypeFinance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserTypeFinance.setText("USER TYPE");
        jPanel4.add(lblUserTypeFinance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        jTabbedPane1.addTab("FINANCE", jPanel4);

        jPanel5.setBackground(new java.awt.Color(19, 213, 236));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileAccounts.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel5.add(lblProfileAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 150, 170));

        lblUsernameAccounts.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsernameAccounts.setForeground(java.awt.Color.white);
        lblUsernameAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameAccounts.setText("USERNAME");
        jPanel5.add(lblUsernameAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 180, -1));

        viewBtn.setBackground(new java.awt.Color(30, 79, 225));
        viewBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        viewBtn.setForeground(java.awt.Color.white);
        viewBtn.setText("VIEW & EDIT USERS");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel5.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 250, 50));

        newUserBtn.setBackground(new java.awt.Color(13, 43, 251));
        newUserBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        newUserBtn.setForeground(java.awt.Color.white);
        newUserBtn.setText("CREATE NEW USER");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });
        jPanel5.add(newUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 50));

        lblUserTypeAccounts.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserTypeAccounts.setForeground(java.awt.Color.white);
        lblUserTypeAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserTypeAccounts.setText("USER TYPE");
        jPanel5.add(lblUserTypeAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        jTabbedPane1.addTab("USER ACCOUNTS", jPanel5);

        jPanel6.setBackground(new java.awt.Color(25, 198, 28));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileKitchen.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel6.add(lblProfileKitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 150, 170));

        lblUsernameKitchen.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsernameKitchen.setForeground(java.awt.Color.white);
        lblUsernameKitchen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameKitchen.setText("USERNAME");
        jPanel6.add(lblUsernameKitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 180, -1));

        lblUserTypeKitchen.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserTypeKitchen.setForeground(java.awt.Color.white);
        lblUserTypeKitchen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserTypeKitchen.setText("USER TYPE");
        jPanel6.add(lblUserTypeKitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        jToggleButton1.setText("DAILY USAGE");
        jPanel6.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 50));

        jToggleButton2.setText("RECEIVE STORE ITEMS");
        jPanel6.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 50));

        jToggleButton3.setText("ORDER STORE ITEMS");
        jPanel6.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 50));

        jTabbedPane1.addTab("KITCHEN", jPanel6);

        jPanel7.setBackground(new java.awt.Color(26, 5, 249));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addDepartments.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        addDepartments.setText("ADD AND EDIT DEPARTMENTS");
        addDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentsActionPerformed(evt);
            }
        });
        jPanel7.add(addDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 310, 50));

        lblProfileDepartments.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel7.add(lblProfileDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 150, 170));

        lblUserTypeDepartments.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUserTypeDepartments.setForeground(java.awt.Color.white);
        lblUserTypeDepartments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserTypeDepartments.setText("USER TYPE");
        jPanel7.add(lblUserTypeDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 180, -1));

        lblUsernameDepartments.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lblUsernameDepartments.setForeground(java.awt.Color.white);
        lblUsernameDepartments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernameDepartments.setText("USERNAME");
        jPanel7.add(lblUsernameDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 180, -1));

        jTabbedPane1.addTab("DEPARTMENTS", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 1090, 490));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("ORDER MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 28, 800, 50));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roomBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomBookingActionPerformed
        this.setVisible(false);
        new BookingRooms(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_roomBookingActionPerformed

    private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed
        this.setVisible(false);
        new ManageClients(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_addClientBtnActionPerformed

    private void mealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsActionPerformed
        this.setVisible(false);
        new HotelMeals(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_mealsActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Hotel System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void hotelRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRoomsActionPerformed
        this.setVisible(false);
        new AvailableRooms(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_hotelRoomsActionPerformed

    private void meals1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meals1ActionPerformed
        this.setVisible(false);
        new SellMeals(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_meals1ActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        this.setVisible(false);
        new User(lblUsernameAccounts.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_newUserBtnActionPerformed

    private void stockInStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInStoreBtnActionPerformed
        this.setVisible(false);
        new StockInStore(lblUsernameStore.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_stockInStoreBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        this.setVisible(false);
        new LoginAdmin(lblUsernameAccounts.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void supplierPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierPaymentBtnActionPerformed
        this.setVisible(false);
        new SuppliersItems(lblUsernameFinance.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_supplierPaymentBtnActionPerformed

    private void issueStoreItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueStoreItemsBtnActionPerformed
        this.setVisible(false);
        new IssueItems(lblUsernameStore.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_issueStoreItemsBtnActionPerformed

    private void salesViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesViewBtnActionPerformed
        this.setVisible(false);
        new ViewSales(lblUsername.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_salesViewBtnActionPerformed

    private void receiveItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveItemsBtnActionPerformed
        this.setVisible(false);
        new ViewSales(lblUsernameStore.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_receiveItemsBtnActionPerformed

    private void addSuppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuppliersBtnActionPerformed
        this.setVisible(false);
        new ViewSales(lblUsernameFinance.getText(),imag,userType).setVisible(true);
    }//GEN-LAST:event_addSuppliersBtnActionPerformed

    private void tenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenderBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenderBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void addDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentsActionPerformed
        
    }//GEN-LAST:event_addDepartmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientBtn;
    private javax.swing.JToggleButton addDepartments;
    private javax.swing.JButton addSuppliersBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton hotelRooms;
    private javax.swing.JButton issueStoreItemsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblProfileAccounts;
    private javax.swing.JLabel lblProfileDepartments;
    private javax.swing.JLabel lblProfileFinance;
    private javax.swing.JLabel lblProfileKitchen;
    private javax.swing.JLabel lblProfileStore;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUserTypeAccounts;
    private javax.swing.JLabel lblUserTypeDepartments;
    private javax.swing.JLabel lblUserTypeFinance;
    private javax.swing.JLabel lblUserTypeKitchen;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameAccounts;
    private javax.swing.JLabel lblUsernameDepartments;
    private javax.swing.JLabel lblUsernameFinance;
    private javax.swing.JLabel lblUsernameKitchen;
    private javax.swing.JLabel lblUsernameStore;
    private javax.swing.JButton meals;
    private javax.swing.JButton meals1;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JButton receiveItemsBtn;
    private javax.swing.JButton roomBooking;
    private javax.swing.JButton salesViewBtn;
    private javax.swing.JButton stockInStoreBtn;
    private javax.swing.JButton supplierPaymentBtn;
    private javax.swing.JButton tenderBtn;
    private javax.swing.JLabel userTypeStore;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
