/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advancedPOS;

import javax.swing.table.DefaultTableModel;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bill
 */
public class supplier extends javax.swing.JPanel {

    Statement s;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form customer
     */
    public supplier() {
        initComponents();
        supplier_table();
    }
    
    public void supplier_table(){
        try {
            pst=Database.myCon().prepareStatement("select * from supplier");
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();
            
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for (int i = 1; i < c; i++) {
                    v.add(rs.getInt("sid"));
                    v.add(rs.getString("supplier_name"));
                    v.add(rs.getString("tp_no"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTPNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtSearchId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchTxtb = new javax.swing.JTextField();
        btnSearchb = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 174, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel1.setText("NAME:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel2.setText("T.P NUMBER:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));
        jPanel2.add(txtTPNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 230, 30));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 230, -1));

        searchBtn.setBackground(new java.awt.Color(19, 191, 50));
        searchBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        searchBtn.setForeground(java.awt.Color.white);
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        clearBtn.setBackground(new java.awt.Color(30, 161, 152));
        clearBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        clearBtn.setForeground(java.awt.Color.white);
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 50));

        updateBtn.setBackground(new java.awt.Color(32, 166, 74));
        updateBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        updateBtn.setForeground(java.awt.Color.white);
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 50));

        saveBtn.setBackground(new java.awt.Color(35, 19, 191));
        saveBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        saveBtn.setForeground(java.awt.Color.white);
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, 50));

        deleteBtn.setBackground(new java.awt.Color(222, 53, 41));
        deleteBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        deleteBtn.setForeground(java.awt.Color.white);
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, 340));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SUPPLIER'S INFO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtSearchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel3.setText("SEARCH ID:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 90));

        jPanel4.setBackground(new java.awt.Color(17, 31, 188));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SUPPLIER'S NAME", "T.P NUMBER"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 491, 360));

        searchTxtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtbKeyPressed(evt);
            }
        });
        jPanel4.add(searchTxtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        btnSearchb.setFont(new java.awt.Font("Ubuntu", 3, 13)); // NOI18N
        btnSearchb.setText("SEARCH WITH NAME");
        btnSearchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 170, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 510, 430));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String eid=txtSearchId.getText();
        try {
            pst=Database.myCon().prepareStatement("select * from supplier where sid LIKE CONCAT('%',?,'%')");
            pst.setString(1, eid);
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();

            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for (int i = 1; i < c; i++) {
                    v.add(rs.getInt("sid"));
                    v.add(rs.getString("supplier_name"));
                    v.add(rs.getString("tp_no"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        txtName.setText("");
        txtTPNumber.setText("");
        txtName.requestFocus();
        supplier_table();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String name=txtName.getText();
        String tp_no=txtTPNumber.getText();
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int selectedIndex=table.getSelectedRow();
        int id=(int)model.getValueAt(selectedIndex, 0);
        try {
            pst=Database.myCon().prepareStatement("update supplier set supplier_name=?, tp_no=? where sid=?");
            pst.setString(1,name);
            pst.setString(2,tp_no);
            pst.setInt(3,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier updated successfully","Success Message",JOptionPane.INFORMATION_MESSAGE);
            txtName.setText("");
            txtTPNumber.setText("");
            txtName.requestFocus();
            supplier_table();
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String name=txtName.getText();
        String tp_no=txtTPNumber.getText();

        try {
            pst=Database.myCon().prepareStatement("insert into supplier (supplier_name,tp_no)values(?,?)");
            pst.setString(1,name);
            pst.setString(2,tp_no);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier inserted successfully into database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            txtName.setText("");
            txtTPNumber.setText("");
            txtName.requestFocus();
            supplier_table();
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int selectedIndex=table.getSelectedRow();
        int id=(int)model.getValueAt(selectedIndex, 0);
        try {
            pst=Database.myCon().prepareStatement("delete from supplier where sid=?");
            pst.setInt(1,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Supplier deleted successfully from database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            txtName.setText("");
            txtTPNumber.setText("");
            txtName.requestFocus();
            supplier_table();
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int selectedIndex=table.getSelectedRow();
        
        txtName.setText(model.getValueAt(selectedIndex, 1).toString());
        txtTPNumber.setText(model.getValueAt(selectedIndex, 2).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void btnSearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbActionPerformed
        String supplier_name=txtSearchId.getText();
        try {
            pst=Database.myCon().prepareStatement("select * from supplier where supplier_name LIKE CONCAT('%',?,'%')");
            pst.setString(1, supplier_name);
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();

            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for (int i = 1; i < c; i++) {
                    v.add(rs.getInt("sid"));
                    v.add(rs.getString("supplier_name"));
                    v.add(rs.getString("tp_no"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchbActionPerformed

    private void searchTxtbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtbKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String supplier_name=txtSearchId.getText();
            try {
                pst=Database.myCon().prepareStatement("select * from supplier where supplier_name LIKE CONCAT('%',?,'%')");
                pst.setString(1, supplier_name);
                rs=pst.executeQuery();
                ResultSetMetaData rsm=rs.getMetaData();
                int c=rsm.getColumnCount();

                DefaultTableModel model=(DefaultTableModel)table.getModel();
                model.setRowCount(0);
                while(rs.next()){
                    Vector v=new Vector();
                    for (int i = 1; i < c; i++) {
                        v.add(rs.getInt("sid"));
                        v.add(rs.getString("supplier_name"));
                        v.add(rs.getString("tp_no"));
                    }
                    model.addRow(v);
                }
            } catch (SQLException ex) {
                Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchTxtbKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSearchb;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxtb;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearchId;
    private javax.swing.JTextField txtTPNumber;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
