/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bill
 */
public class Home extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    public Home(String username, BufferedImage imag) {
        initComponents();
        Connect();
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("emmanuel-chigbo-jr7R01lOn1Y-unsplash.jpg")).getImage().getScaledInstance(1260, 660, Image.SCALE_SMOOTH)));
        this.username=username;
        lblUsername.setText(username);
        this.imag=imag;
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(190, 220, Image.SCALE_SMOOTH)));
    }
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/gym", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        trainersBtn = new javax.swing.JToggleButton();
        editAdultsBtn = new javax.swing.JToggleButton();
        editYoungBtn = new javax.swing.JToggleButton();
        exitBtn = new javax.swing.JToggleButton();
        youngCustomers = new javax.swing.JToggleButton();
        customersBtn = new javax.swing.JToggleButton();
        youngPayBtn = new javax.swing.JToggleButton();
        payTrainersBtn = new javax.swing.JToggleButton();
        viewUsers = new javax.swing.JToggleButton();
        adultPay = new javax.swing.JToggleButton();
        editTrainers = new javax.swing.JToggleButton();
        lblProfile = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        addUserBtn = new javax.swing.JToggleButton();
        aboutBtn = new javax.swing.JToggleButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1280, 680, 680, 680));
        setMaximumSize(new java.awt.Dimension(1280, 680));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 43, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trainersBtn.setBackground(new java.awt.Color(20, 70, 253));
        trainersBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        trainersBtn.setForeground(java.awt.Color.white);
        trainersBtn.setText("ADD TRAINERS/COACHES");
        trainersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(trainersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 50));

        editAdultsBtn.setBackground(new java.awt.Color(20, 70, 253));
        editAdultsBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        editAdultsBtn.setForeground(java.awt.Color.white);
        editAdultsBtn.setText("EDIT-DELETE ADULT CUSTOMERS");
        editAdultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdultsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editAdultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 50));

        editYoungBtn.setBackground(new java.awt.Color(20, 70, 253));
        editYoungBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        editYoungBtn.setForeground(java.awt.Color.white);
        editYoungBtn.setText("EDIT-DELETE YOUNG CUSTOMERS");
        editYoungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editYoungBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editYoungBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 50));

        exitBtn.setBackground(new java.awt.Color(253, 32, 20));
        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        exitBtn.setForeground(java.awt.Color.white);
        exitBtn.setText("EXIT SYSTEM");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, 50));

        youngCustomers.setBackground(new java.awt.Color(20, 70, 253));
        youngCustomers.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        youngCustomers.setForeground(java.awt.Color.white);
        youngCustomers.setText("ADD YOUNG CUSTOMERS");
        youngCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youngCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(youngCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 50));

        customersBtn.setBackground(new java.awt.Color(20, 70, 253));
        customersBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        customersBtn.setForeground(java.awt.Color.white);
        customersBtn.setText("ADD ADULT CUSTOMERS");
        customersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(customersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 50));

        youngPayBtn.setBackground(new java.awt.Color(20, 70, 253));
        youngPayBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        youngPayBtn.setForeground(java.awt.Color.white);
        youngPayBtn.setText("PAYMENT - YOUNG CUSTOMERS");
        youngPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youngPayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(youngPayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 280, 50));

        payTrainersBtn.setBackground(new java.awt.Color(20, 70, 253));
        payTrainersBtn.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        payTrainersBtn.setForeground(java.awt.Color.white);
        payTrainersBtn.setText("PAY TRAINERS");
        payTrainersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payTrainersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(payTrainersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 280, 50));

        viewUsers.setBackground(new java.awt.Color(227, 48, 14));
        viewUsers.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        viewUsers.setForeground(java.awt.Color.white);
        viewUsers.setText("VIEW AND EDIT USERS");
        viewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersActionPerformed(evt);
            }
        });
        jPanel1.add(viewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 280, 50));

        adultPay.setBackground(new java.awt.Color(20, 70, 253));
        adultPay.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        adultPay.setForeground(java.awt.Color.white);
        adultPay.setText("PAYMENT - ADULT CUSTOMERS");
        adultPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultPayActionPerformed(evt);
            }
        });
        jPanel1.add(adultPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 280, 50));

        editTrainers.setBackground(new java.awt.Color(20, 70, 253));
        editTrainers.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        editTrainers.setForeground(java.awt.Color.white);
        editTrainers.setText("EDIT-DELETE TRAINERS");
        editTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTrainersActionPerformed(evt);
            }
        });
        jPanel1.add(editTrainers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 50));

        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 170, 210));

        lblUsername.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblUsername.setForeground(java.awt.Color.white);
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USERNAME");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 180, -1));

        addUserBtn.setBackground(new java.awt.Color(33, 217, 24));
        addUserBtn.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        addUserBtn.setForeground(java.awt.Color.white);
        addUserBtn.setText("ADD USERS");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 280, 50));

        aboutBtn.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        aboutBtn.setText("ABOUT");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 860, 390));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trainersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainersBtnActionPerformed
        this.setVisible(false);
        //new Trainers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_trainersBtnActionPerformed

    private void editAdultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdultsBtnActionPerformed
        this.setVisible(false);
        //new EditDeleteAdultCustomers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_editAdultsBtnActionPerformed

    private void editYoungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editYoungBtnActionPerformed
        this.setVisible(false);
        //new EditDeleteYoungCustomers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_editYoungBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Do you want to exit system?","GYM Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void youngCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youngCustomersActionPerformed
        this.setVisible(false);
       // new YoungCustomers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_youngCustomersActionPerformed

    private void customersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersBtnActionPerformed
        this.setVisible(false);
        //new Customers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_customersBtnActionPerformed

    private void youngPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youngPayBtnActionPerformed
        this.setVisible(false);
        //new PaymentYoungCustomers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_youngPayBtnActionPerformed

    private void payTrainersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTrainersBtnActionPerformed
        this.setVisible(false);
        //new PayTrainers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_payTrainersBtnActionPerformed

    private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Are you an admin??? Only the admin is authorised to edit and delete users from this system!!!","WARNING!!!",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            //new LoginAdmin(lblUsername.getText(),imag).setVisible(true);
        }
    }//GEN-LAST:event_viewUsersActionPerformed

    private void adultPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultPayActionPerformed
        this.setVisible(false);
        //new PayementAdultCustomers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_adultPayActionPerformed

    private void editTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTrainersActionPerformed
        this.setVisible(false);
        //new EditDeleteTrainers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_editTrainersActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        this.setVisible(false);
       // new User(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        this.setVisible(false);
        //new About(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aboutBtn;
    private javax.swing.JToggleButton addUserBtn;
    private javax.swing.JToggleButton adultPay;
    private javax.swing.JToggleButton customersBtn;
    private javax.swing.JToggleButton editAdultsBtn;
    private javax.swing.JToggleButton editTrainers;
    private javax.swing.JToggleButton editYoungBtn;
    private javax.swing.JToggleButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JToggleButton payTrainersBtn;
    private javax.swing.JToggleButton trainersBtn;
    private javax.swing.JToggleButton viewUsers;
    private javax.swing.JToggleButton youngCustomers;
    private javax.swing.JToggleButton youngPayBtn;
    // End of variables declaration//GEN-END:variables
}
