/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotelmanagement.system;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bill
 */
public class HotelMeals extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form ManageClients
     */
    public HotelMeals() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    public HotelMeals(String username,BufferedImage imag) {
        initComponents();
        this.username=username;
        lblUsername.setText(username);
        this.imag=imag;
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("emmanuel-chigbo-jr7R01lOn1Y-unsplash.jpg")).getImage().getScaledInstance(1240, 720, Image.SCALE_SMOOTH)));
        Connect();
        Auto_id();
        Meal_Table();
    }
    
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*public void Connect(){
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:Hotel.db");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    public void Auto_id(){
        try {
            Statement s=con.createStatement();
            rs=s.executeQuery("select MAX(mealNo) from meals");
            rs.next();
            rs.getString("MAX(mealNo)");
            if(rs.getString("MAX(mealNo)")==null){
                lblMealNo.setText("ML001");
            }else{
                long id=Long.parseLong(rs.getString("MAX(mealNo)").substring(2,rs.getString("MAX(mealNo)").length()));
                id++;
                lblMealNo.setText("ML"+String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Meal_Table(){
        try {
            pst=con.prepareStatement("select * from meals");
            rs=pst.executeQuery();
            ResultSetMetaData rsm=rs.getMetaData();
            int c=rsm.getColumnCount();
            
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<c;i++){
                    v.add(rs.getString("mealNo"));
                    v.add(rs.getString("mealName"));
                    v.add(rs.getString("description"));
                    v.add(rs.getString("price"));
                    v.add(rs.getString("sellingPrice"));
                    v.add(rs.getString("quantity"));
                }
                model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSellingPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lblMealNo = new javax.swing.JLabel();
        txtMealName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAllocate1 = new javax.swing.JButton();
        bookRoomBtn = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANAGE CLIENTS");
        setMaximizedBounds(new java.awt.Rectangle(1236, 718, 718, 718));
        setMinimumSize(new java.awt.Dimension(1236, 718));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(38, 16, 241));
        lblUsername.setText("USERNAME");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 170, -1));

        jPanel1.setBackground(new java.awt.Color(60, 151, 195));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("MEAL NO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
        });
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 260, 40));

        jLabel3.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("DESCRIPTION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("MEAL PRICE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 260, 40));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 260, 40));

        jLabel5.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("QUANTITY:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        txtSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSellingPriceKeyPressed(evt);
            }
        });
        jPanel1.add(txtSellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, 40));

        jLabel6.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("SELLING PRICE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEAL NO", "MEAL NAME", "DESCRIPTION", "MEAL PRICE", "SELLING PRICE", "QUANTITY"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 740, 410));

        homeBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(36, 39, 246));
        homeBtn.setText("HOME PAGE");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 130, 50));

        addBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 22, 255));
        addBtn.setText("ADD MEAL");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 150, 50));

        editBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(33, 158, 33));
        editBtn.setText("EDIT MEAL");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 130, 50));

        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(238, 13, 24));
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 130, 50));

        clearBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(128, 13, 238));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 130, 50));

        deleteBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(238, 13, 24));
        deleteBtn.setText("DELETE MEAL");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 160, 50));

        lblMealNo.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblMealNo.setForeground(java.awt.Color.white);
        lblMealNo.setText("MEAL NUMBER");
        lblMealNo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 3));
        jPanel1.add(lblMealNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 250, 40));

        txtMealName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMealNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtMealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 260, 40));

        jLabel7.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("MEAL NAME:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnAllocate1.setBackground(new java.awt.Color(228, 32, 32));
        btnAllocate1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAllocate1.setForeground(java.awt.Color.white);
        btnAllocate1.setText("TABLE TO PDF");
        btnAllocate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllocate1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAllocate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 510, 170, 50));

        bookRoomBtn.setBackground(new java.awt.Color(41, 184, 40));
        bookRoomBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bookRoomBtn.setForeground(java.awt.Color.white);
        bookRoomBtn.setText("TABLE TO EXCEL");
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 170, 50));

        lblProfile.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1210, 590));

        jLabel1.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 13, 249));
        jLabel1.setText("HOTEL MEALS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 50));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        new Main(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String mealNo=lblMealNo.getText();       
        try {
            pst=con.prepareStatement("delete from clients where mealNo=?");
            pst.setString(1,mealNo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Meal Deleted Successfully from database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            Auto_id();
            txtMealName.setText("");
            txtDescription.setText("");
            txtPrice.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtMealName.requestFocus();
            Meal_Table();
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Hotel System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String mealNo=lblMealNo.getText();
        String mealName=txtMealName.getText();
        String description=txtDescription.getText();
        String price=txtPrice.getText();
        String sellingPrice=txtSellingPrice.getText();
        String quantity=txtQty.getText();
        
        if(mealName.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal name, null meal names cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtMealName.requestFocus();
        }else if(description.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal description, null meal descriptions cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtDescription.requestFocus();
        }else if(price.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal price, null meal prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtPrice.requestFocus();
        }else if(sellingPrice.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter selling price, null selling prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtSellingPrice.requestFocus();
        }else if(quantity.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter quantity, null quantities cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtQty.requestFocus();
        }else{
        try {
            pst=con.prepareStatement("insert into meals (mealNo,mealName,description,price,sellingPrice,quantity)values(?,?,?,?,?,?)");
            pst.setString(1,mealNo);
            pst.setString(2,mealName);
            pst.setString(3,description);
            pst.setString(4,price);
            pst.setString(5,sellingPrice);
            pst.setString(6,quantity);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Meal Added Successfully into database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            Auto_id();
            txtMealName.setText("");
            txtDescription.setText("");
            txtPrice.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtMealName.requestFocus();
            Meal_Table();
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        txtMealName.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        txtSellingPrice.setText("");
        txtQty.setText("");
        txtMealName.requestFocus();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        String mealNo=lblMealNo.getText();
        String mealName=txtMealName.getText();
        String description=txtDescription.getText();
        String price=txtPrice.getText();
        String sellingPrice=txtSellingPrice.getText();
        String quantity=txtQty.getText();
        
        if(mealName.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal name, null meal names cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtMealName.requestFocus();
        }else if(description.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal description, null meal descriptions cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtDescription.requestFocus();
        }else if(price.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal price, null meal prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtPrice.requestFocus();
        }else if(sellingPrice.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter selling price, null selling prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtSellingPrice.requestFocus();
        }else if(quantity.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter quantity, null quantities cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtQty.requestFocus();
        }else{
        try {
            pst=con.prepareStatement("update meals set mealName=?, description=?, price=?, sellingPrice=?, quantity=? where mealNo=?");
            pst.setString(1,mealName);
            pst.setString(2,description);
            pst.setString(3,price);
            pst.setString(4,sellingPrice);
            pst.setString(5,quantity);
            pst.setString(6,mealNo);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Meal Updated Successfully on database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            Auto_id();
            txtMealName.setText("");
            txtDescription.setText("");
            txtPrice.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtMealName.requestFocus();
            Meal_Table();
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_editBtnActionPerformed
    
    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPrice.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtPrice.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtMealName.requestFocus();
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtSellingPrice.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtSellingPrice.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtDescription.requestFocus();
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    private void txtSellingPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingPriceKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtQty.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtQty.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtPrice.requestFocus();
        }
    }//GEN-LAST:event_txtSellingPriceKeyPressed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String mealNo=lblMealNo.getText();
        String mealName=txtMealName.getText();
        String description=txtDescription.getText();
        String price=txtPrice.getText();
        String sellingPrice=txtSellingPrice.getText();
        String quantity=txtQty.getText();
        
        if(mealName.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal name, null meal names cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtMealName.requestFocus();
        }else if(description.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal description, null meal descriptions cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtDescription.requestFocus();
        }else if(price.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter meal price, null meal prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtPrice.requestFocus();
        }else if(sellingPrice.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter selling price, null selling prices cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtSellingPrice.requestFocus();
        }else if(quantity.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter quantity, null quantities cannot be submitted","Submission Error!!",JOptionPane.CANCEL_OPTION);
            txtQty.requestFocus();
        }else{
        try {
            pst=con.prepareStatement("insert into meals (mealNo,mealName,description,price,sellingPrice,quantity)values(?,?,?,?,?,?)");
            pst.setString(1,mealNo);
            pst.setString(2,mealName);
            pst.setString(3,description);
            pst.setString(4,price);
            pst.setString(5,sellingPrice);
            pst.setString(6,quantity);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Meal Added Successfully into database","Success Message",JOptionPane.INFORMATION_MESSAGE);
            Auto_id();
            txtMealName.setText("");
            txtDescription.setText("");
            txtPrice.setText("");
            txtSellingPrice.setText("");
            txtQty.setText("");
            txtMealName.requestFocus();
            Meal_Table();
        } catch (SQLException ex) {
            Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtMealName.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtSellingPrice.requestFocus();
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtMealNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMealNameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDescription.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            txtDescription.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            txtQty.requestFocus();
        }
    }//GEN-LAST:event_txtMealNameKeyPressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int selectedIndex=table.getSelectedRow();
        lblMealNo.setText(model.getValueAt(selectedIndex, 0).toString());
        txtMealName.setText(model.getValueAt(selectedIndex, 1).toString());
        txtDescription.setText(model.getValueAt(selectedIndex, 2).toString());
        txtPrice.setText(model.getValueAt(selectedIndex, 3).toString());
        txtSellingPrice.setText(model.getValueAt(selectedIndex, 4).toString());
        txtQty.setText(model.getValueAt(selectedIndex, 5).toString());
        
        editBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        editBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void btnAllocate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllocate1ActionPerformed
        MessageFormat header=new MessageFormat("HOTEL MEALS");
        MessageFormat footer=new MessageFormat("page {0}");
        try {
            table.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (PrinterException ex) {
            Logger.getLogger(AllocateRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAllocate1ActionPerformed

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setDialogTitle("Export table to an excel file.csv format?");
        int userSelection=fileChooser.showSaveDialog(this);
        if(userSelection==JFileChooser.APPROVE_OPTION){
            File file=fileChooser.getSelectedFile();
            
            FileWriter writer;
            try {
                writer=new FileWriter(file);
                BufferedWriter bWriter=new BufferedWriter(writer);
                for (int i = 0; i < table.getRowCount(); i++) {
                    for (int j = 0; j < table.getColumnCount(); j++) {
                        bWriter.write(table.getValueAt(i, j).toString()+",");
                    }
                    bWriter.newLine();
                }
                bWriter.close();
                writer.close();
                JOptionPane.showMessageDialog(this, "Table exported successfully into an excel file .csv format");
                
            } catch (IOException ex) {
                Logger.getLogger(HotelMeals.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bookRoomBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelMeals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JButton btnAllocate1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblMealNo;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtMealName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
