/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotelmanagement.system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bill
 */
public class Main extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    public Main(String username, BufferedImage imag) {
        initComponents();
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("emmanuel-chigbo-jr7R01lOn1Y-unsplash.jpg")).getImage().getScaledInstance(1210, 630, Image.SCALE_SMOOTH)));
        this.username=username;
        lblUsername.setText(username);
        this.imag=imag;
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(150, 170, Image.SCALE_SMOOTH)));
        Connect();
    }

    /*public void Connect(){
        try {
            Class.forName("org.sqlite.JDBC");
            con=DriverManager.getConnection("jdbc:sqlite:Hotel.db");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/Hotel","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        hotelRooms = new javax.swing.JButton();
        roomBooking = new javax.swing.JButton();
        addClientBtn = new javax.swing.JButton();
        meals = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        meals1 = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        newUserBtn = new javax.swing.JButton();
        stockBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        salesViewBtn = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        sellMealsMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        clientMenu = new javax.swing.JMenuItem();
        bookingMenu = new javax.swing.JMenuItem();
        mealsMenu = new javax.swing.JMenuItem();
        hotelRoomsMenu = new javax.swing.JMenuItem();
        stockInStoreMenu = new javax.swing.JMenuItem();
        supplierMenu = new javax.swing.JMenuItem();
        newUserMenu = new javax.swing.JMenuItem();
        issueMenu = new javax.swing.JMenuItem();
        editUsers = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME PAGE");
        setMaximizedBounds(new java.awt.Rectangle(1207, 656, 656, 656));
        setMaximumSize(new java.awt.Dimension(1207, 656));
        setMinimumSize(new java.awt.Dimension(1207, 656));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(142, 54, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(38, 16, 241));
        lblUsername.setText("USERNAME");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 170, -1));

        hotelRooms.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        hotelRooms.setForeground(new java.awt.Color(13, 52, 248));
        hotelRooms.setText("HOTEL ROOMS");
        hotelRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRoomsActionPerformed(evt);
            }
        });
        jPanel1.add(hotelRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 230, 50));

        roomBooking.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        roomBooking.setForeground(new java.awt.Color(13, 52, 248));
        roomBooking.setText("ROOM BOOKING");
        roomBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomBookingActionPerformed(evt);
            }
        });
        jPanel1.add(roomBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 50));

        addClientBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addClientBtn.setForeground(new java.awt.Color(13, 52, 248));
        addClientBtn.setText("ADD CLIENT");
        addClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addClientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 50));

        meals.setBackground(new java.awt.Color(41, 194, 52));
        meals.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        meals.setForeground(java.awt.Color.white);
        meals.setText("AVALABLE MEALS");
        meals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsActionPerformed(evt);
            }
        });
        jPanel1.add(meals, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 50));

        exitBtn.setBackground(new java.awt.Color(247, 63, 9));
        exitBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        exitBtn.setForeground(java.awt.Color.white);
        exitBtn.setText("EXIT SYSTEM");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 230, 50));

        meals1.setBackground(new java.awt.Color(15, 19, 247));
        meals1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        meals1.setForeground(java.awt.Color.white);
        meals1.setText("SELL MEALS");
        meals1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meals1ActionPerformed(evt);
            }
        });
        jPanel1.add(meals1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 50));

        aboutBtn.setBackground(new java.awt.Color(238, 21, 21));
        aboutBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        aboutBtn.setForeground(java.awt.Color.white);
        aboutBtn.setText("ABOUT");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 130, 40));

        newUserBtn.setBackground(new java.awt.Color(13, 43, 251));
        newUserBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        newUserBtn.setForeground(java.awt.Color.white);
        newUserBtn.setText("CREATE NEW USER");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, 50));

        stockBtn.setBackground(new java.awt.Color(220, 15, 15));
        stockBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        stockBtn.setForeground(java.awt.Color.white);
        stockBtn.setText("STOCK IN STORE");
        stockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBtnActionPerformed(evt);
            }
        });
        jPanel1.add(stockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 250, 50));

        viewBtn.setBackground(new java.awt.Color(30, 79, 225));
        viewBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        viewBtn.setForeground(java.awt.Color.white);
        viewBtn.setText("VIEW & EDIT USERS");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 250, 50));

        supplierBtn.setBackground(java.awt.Color.blue);
        supplierBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        supplierBtn.setForeground(java.awt.Color.white);
        supplierBtn.setText("SUPPLIERS BASE");
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(supplierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 250, 50));

        issueBtn.setBackground(new java.awt.Color(34, 44, 246));
        issueBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        issueBtn.setForeground(java.awt.Color.white);
        issueBtn.setText("ISSUE STORE ITEMS");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });
        jPanel1.add(issueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 250, 50));

        salesViewBtn.setBackground(new java.awt.Color(15, 47, 240));
        salesViewBtn.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        salesViewBtn.setForeground(java.awt.Color.white);
        salesViewBtn.setText("VIEW MEAL SALES");
        salesViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(salesViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 250, 50));

        lblProfile.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 150, 170));

        lblUsername1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblUsername1.setForeground(java.awt.Color.white);
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername1.setText("USERNAME");
        jPanel1.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 860, 440));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 630));

        jMenu3.setText("Manage>");
        jMenu3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N

        sellMealsMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        sellMealsMenu.setText("SELL MEALS");
        sellMealsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMealsMenuActionPerformed(evt);
            }
        });
        jMenu3.add(sellMealsMenu);
        jMenu3.add(jSeparator1);
        jMenu3.add(jSeparator2);

        clientMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        clientMenu.setText("ADD CLIENT");
        clientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientMenuActionPerformed(evt);
            }
        });
        jMenu3.add(clientMenu);

        bookingMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingMenu.setText("ROOM BOOKING");
        bookingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingMenuActionPerformed(evt);
            }
        });
        jMenu3.add(bookingMenu);

        mealsMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        mealsMenu.setText("AVAILABLE MEALS");
        mealsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsMenuActionPerformed(evt);
            }
        });
        jMenu3.add(mealsMenu);

        hotelRoomsMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        hotelRoomsMenu.setText("HOTEL ROOMS");
        hotelRoomsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelRoomsMenuActionPerformed(evt);
            }
        });
        jMenu3.add(hotelRoomsMenu);

        stockInStoreMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        stockInStoreMenu.setText("STOCK IN STORE");
        stockInStoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInStoreMenuActionPerformed(evt);
            }
        });
        jMenu3.add(stockInStoreMenu);

        supplierMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        supplierMenu.setText("SUPPLIERS BASE");
        supplierMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMenuActionPerformed(evt);
            }
        });
        jMenu3.add(supplierMenu);

        newUserMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        newUserMenu.setText("NEW USER");
        newUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserMenuActionPerformed(evt);
            }
        });
        jMenu3.add(newUserMenu);

        issueMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        issueMenu.setText("ISSUE ITEMS");
        issueMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueMenuActionPerformed(evt);
            }
        });
        jMenu3.add(issueMenu);

        editUsers.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        editUsers.setText("EDIT USERS");
        editUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsersActionPerformed(evt);
            }
        });
        jMenu3.add(editUsers);

        aboutMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        aboutMenu.setText("ABOUT");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu3.add(aboutMenu);

        exitMenu.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        exitMenu.setText("EXIT");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu3.add(exitMenu);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellMealsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMealsMenuActionPerformed
        this.setVisible(false);
        new SellMeals(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_sellMealsMenuActionPerformed

    private void clientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientMenuActionPerformed
        this.setVisible(false);
        new ManageClients(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_clientMenuActionPerformed

    private void roomBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomBookingActionPerformed
        this.setVisible(false);
        new BookingRooms(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_roomBookingActionPerformed

    private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed
        this.setVisible(false);
        new ManageClients(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_addClientBtnActionPerformed

    private void mealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsActionPerformed
        this.setVisible(false);
        new HotelMeals(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_mealsActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Hotel System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void hotelRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRoomsActionPerformed
        this.setVisible(false);
        new AvailableRooms(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_hotelRoomsActionPerformed

    private void meals1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meals1ActionPerformed
        this.setVisible(false);
        new SellMeals(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_meals1ActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        this.setVisible(false);
        new About(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        this.setVisible(false);
        new User(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_newUserBtnActionPerformed

    private void stockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBtnActionPerformed
        this.setVisible(false);
        new StockInStore(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_stockBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        this.setVisible(false);
        new LoginAdmin(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        this.setVisible(false);
        new SuppliersItems(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        this.setVisible(false);
        new IssueItems(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_issueBtnActionPerformed

    private void bookingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingMenuActionPerformed
        this.setVisible(false);
        new BookingRooms(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_bookingMenuActionPerformed

    private void mealsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsMenuActionPerformed
        this.setVisible(false);
        new HotelMeals(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_mealsMenuActionPerformed

    private void hotelRoomsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelRoomsMenuActionPerformed
        this.setVisible(false);
        new AvailableRooms(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_hotelRoomsMenuActionPerformed

    private void stockInStoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInStoreMenuActionPerformed
        this.setVisible(false);
        new StockInStore(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_stockInStoreMenuActionPerformed

    private void supplierMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMenuActionPerformed
        this.setVisible(false);
        new SuppliersItems(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_supplierMenuActionPerformed

    private void newUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserMenuActionPerformed
        this.setVisible(false);
        new User(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_newUserMenuActionPerformed

    private void issueMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueMenuActionPerformed
        this.setVisible(false);
        new IssueItems(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_issueMenuActionPerformed

    private void editUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsersActionPerformed
        this.setVisible(false);
        new EditUsers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_editUsersActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        this.setVisible(false);
        new About(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Do yo want to exit Hotel System?","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuActionPerformed

    private void salesViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesViewBtnActionPerformed
        this.setVisible(false);
        new ViewSales(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_salesViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JButton addClientBtn;
    private javax.swing.JMenuItem bookingMenu;
    private javax.swing.JMenuItem clientMenu;
    private javax.swing.JMenuItem editUsers;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JButton hotelRooms;
    private javax.swing.JMenuItem hotelRoomsMenu;
    private javax.swing.JButton issueBtn;
    private javax.swing.JMenuItem issueMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JButton meals;
    private javax.swing.JButton meals1;
    private javax.swing.JMenuItem mealsMenu;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JMenuItem newUserMenu;
    private javax.swing.JButton roomBooking;
    private javax.swing.JButton salesViewBtn;
    private javax.swing.JMenuItem sellMealsMenu;
    private javax.swing.JButton stockBtn;
    private javax.swing.JMenuItem stockInStoreMenu;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JMenuItem supplierMenu;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
