/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_management_system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class More extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public More() {
        initComponents();
    }
    
    String username;
    BufferedImage imag;
    public More(String username,BufferedImage imag) {
        initComponents();
        this.username=username;
        this.imag=imag;
        lblUsername.setText(username);
        lblBackground.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("../Images/caleb-woods-fulXJYIvRi8-unsplash.jpg")).getImage().getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), Image.SCALE_SMOOTH)));
        lblProfile.setIcon(new ImageIcon(new javax.swing.ImageIcon(imag).getImage().getScaledInstance(lblProfile.getWidth(), lblProfile.getHeight(), Image.SCALE_SMOOTH)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        paidBooksGroups = new javax.swing.JButton();
        paidBooksTeachers = new javax.swing.JButton();
        paidBooksStudents = new javax.swing.JButton();
        lostBooksTeachers = new javax.swing.JButton();
        lostBooksGroups = new javax.swing.JButton();
        lostBooksStudents = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        editUsersBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MORE");
        setMaximizedBounds(new java.awt.Rectangle(1300, 720, 720, 720));
        setMinimumSize(new java.awt.Dimension(1300, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("USERNAME");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 120, -1));

        lblProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 100, 110));

        exitBtn.setBackground(new java.awt.Color(255, 0, 0));
        exitBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("EXIT SYSTEM");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 280, 50));

        paidBooksGroups.setBackground(new java.awt.Color(0, 0, 255));
        paidBooksGroups.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        paidBooksGroups.setForeground(new java.awt.Color(255, 255, 255));
        paidBooksGroups.setText("PAID BOOKS:- GROUPS");
        paidBooksGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBooksGroupsActionPerformed(evt);
            }
        });
        jPanel1.add(paidBooksGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 50));

        paidBooksTeachers.setBackground(new java.awt.Color(0, 0, 255));
        paidBooksTeachers.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        paidBooksTeachers.setForeground(new java.awt.Color(255, 255, 255));
        paidBooksTeachers.setText("PAID BOOKS:- TEACHERS");
        paidBooksTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBooksTeachersActionPerformed(evt);
            }
        });
        jPanel1.add(paidBooksTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 280, 50));

        paidBooksStudents.setBackground(new java.awt.Color(0, 0, 255));
        paidBooksStudents.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        paidBooksStudents.setForeground(new java.awt.Color(255, 255, 255));
        paidBooksStudents.setText("PAID BOOKS STUDENTS");
        paidBooksStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBooksStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(paidBooksStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 50));

        lostBooksTeachers.setBackground(new java.awt.Color(0, 0, 255));
        lostBooksTeachers.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lostBooksTeachers.setForeground(new java.awt.Color(255, 255, 255));
        lostBooksTeachers.setText("LOST BOOKS:- TEACHERS");
        lostBooksTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBooksTeachersActionPerformed(evt);
            }
        });
        jPanel1.add(lostBooksTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 50));

        lostBooksGroups.setBackground(new java.awt.Color(0, 0, 255));
        lostBooksGroups.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lostBooksGroups.setForeground(new java.awt.Color(255, 255, 255));
        lostBooksGroups.setText("LOST BOOKS:- GROUPS");
        lostBooksGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBooksGroupsActionPerformed(evt);
            }
        });
        jPanel1.add(lostBooksGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, 50));

        lostBooksStudents.setBackground(new java.awt.Color(0, 0, 255));
        lostBooksStudents.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lostBooksStudents.setForeground(new java.awt.Color(255, 255, 255));
        lostBooksStudents.setText("LOST BOOKS:- STUDENTS");
        lostBooksStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBooksStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(lostBooksStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, 50));

        homeBtn.setBackground(new java.awt.Color(51, 102, 0));
        homeBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 280, 50));

        editUsersBtn.setBackground(new java.awt.Color(0, 0, 255));
        editUsersBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        editUsersBtn.setForeground(new java.awt.Color(255, 255, 255));
        editUsersBtn.setText("EDIT USERS");
        editUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 280, 50));

        aboutBtn.setBackground(new java.awt.Color(0, 0, 255));
        aboutBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("ABOUT");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 280, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 1160, 580));

        jLabel9.setFont(new java.awt.Font("SansSerif", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 810, -1));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 1300, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Do yo want to exit system","Confirm Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void paidBooksGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBooksGroupsActionPerformed
        this.setVisible(false);
        new PaidGroups(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_paidBooksGroupsActionPerformed

    private void paidBooksTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBooksTeachersActionPerformed
        this.setVisible(false);
        new PaidTeachers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_paidBooksTeachersActionPerformed

    private void paidBooksStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBooksStudentsActionPerformed
        this.setVisible(false);
        new PaidGStudents(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_paidBooksStudentsActionPerformed

    private void lostBooksTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBooksTeachersActionPerformed
        this.setVisible(false);
        new LostBooksTeachers(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_lostBooksTeachersActionPerformed

    private void lostBooksGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBooksGroupsActionPerformed
        this.setVisible(false);
        new LostBooksGroups(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_lostBooksGroupsActionPerformed

    private void lostBooksStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBooksStudentsActionPerformed
        this.setVisible(false);
        new LostBooksStudents(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_lostBooksStudentsActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        new Home(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void editUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsersBtnActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Only admins are allowed to edit users on this system. Are you an admin??","Confirm if you are an admin",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            this.setVisible(false);
            new Login2(lblUsername.getText(),imag).setVisible(true);
        }
    }//GEN-LAST:event_editUsersBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        this.setVisible(false);
        new About(lblUsername.getText(),imag).setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new More().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton editUsersBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JButton lostBooksGroups;
    private javax.swing.JButton lostBooksStudents;
    private javax.swing.JButton lostBooksTeachers;
    private javax.swing.JButton paidBooksGroups;
    private javax.swing.JButton paidBooksStudents;
    private javax.swing.JButton paidBooksTeachers;
    // End of variables declaration//GEN-END:variables
}
